### ISSUE TITLE
release branch to target should be a org secret

### ISSUE THREAD

**Issue by shawn-hurley** [konveyor/bz-github-action#2]
It will be much easier to only have to update the mapping at the repo level vs editing the workflow directly

**Comment by rayfordj** [comment]
`secrets.BRANCH_TO_RELEASE`

**Comment by rayfordj** [comment]
```
'release-1.3.2:1.3.z,release-1.4.4:1.4.4,release-1.4.3:1.4.3,release-1.4.0:1.4.0,release-1.4.5:1.4.5,release-1.5.0:1.5.0,konveyor-dev:1.5.z,master:1.5.z'
```

**Comment by rayfordj** [comment]
openshift/oadp-operator
openshift/openshift-velero-plugin
openshift/restic
openshift/velero
openshift/velero-plugin-for-aws
openshift/velero-plugin-for-gcp
openshift/velero-plugin-for-microsoft-azure

The listed repos are no longer under Konveyor org, because they've been moved to OpenShift.  I don't have the necessary privileges to create Org secrets under OpenShift, so I'm not sure at the moment how we want to manage these repos with regard to our PR-BZ automation.

**Comment by shawn-hurley** [comment]
I think that these should probably be managed by openshift-ci BZ automation.

**Comment by rayfordj** [comment]
```
'release-1.3.2:1.3.z,release-1.4.4:1.4.4,release-1.4.3:1.4.3,release-1.4.0:1.4.0,release-1.4.5:1.4.5,release-1.4.6:1.4.6,release-1.5.0:1.5.0,konveyor-dev:1.5.z,master:1.5.z'
```

**Comment by rayfordj** [comment]
```
'release-1.3.2:1.3.z,release-1.4.4:1.4.4,release-1.4.3:1.4.3,release-1.4.0:1.4.0,release-1.4.5:1.4.5,release-1.4.6:1.4.6,release-1.4.7:1.4.7,release-1.5.0:1.5.0,konveyor-dev:1.6.z,master:1.6.z'
```

**Comment by rayfordj** [comment]
Carrying the plain-text mapping of the secret in [MTC_MAP.md](https://github.com/konveyor/bz-github-action/blob/master/MTC_MAP.md) for reference and will update it going forward to keep a record of the latest value in [BRANCH_TO_RELEASE](https://github.com/organizations/konveyor/settings/secrets/actions/BRANCH_TO_RELEASE).
